name: Rust Check

on:
  pull_request:
    branches: [ "dev", "main", "ultradev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cargo Check
      run: cargo check
